name: Daily Story Fetch

on:
  schedule:
    - cron: "0 19 * * *"  # Run every day at 07:00 UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install Ruby dependencies
        run: gem install nokogiri pry

      - name: Run fetch script
        run: ruby fetch.rb

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add stories.json
          git commit -m "Auto-update stories.json [CI]" || echo "No changes"
          git push
